### ISSUE TITLE
ROADMAP 2020

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#225]
Per @nikolaiwarner in `#cabal-dev`:

- [ ] finish cabal ui.... which will give us components for everything, really sane and understandable redux with redux-tookit, and easy theming with styled-components
- [ ] split the code in electron between the render and main processes
- [ ] improve the build/release workflow
- [ ] favoriting channels
- [ ] scrolling back in history
- [ ] editable messages
